### ISSUE TITLE
Wrong url to check jinad is properly set up

### ISSUE THREAD

**Issue by samjoy** [jina-ai/docs#117]
In https://docs.jina.ai/master/chapters/remote/jinad.html, under the Usage->Prerequisites section->2nd paragraph, it says to visit http://3.16.166.3:8000/alive to check if jinad is properly set up. The url does not work. I think it should be http://3.16.166.3:8000/status

**Comment by bwanglzu** [comment]
as we discussed, @deepankarm will fix this together with other changes. thanks so much @samjoy !

> It should just be http://3.16.166.3:8000/

**Comment by FionnD** [comment]
@bwanglzu any update on this?

**Comment by bwanglzu** [comment]
@FionnD , as was mentioned above, @deepankarm is going to take care of this.
