### ISSUE TITLE
let jina bot commit to master branch

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/docs#123]
Once after a release, we need to update `versions` file and push to `master` branch. While `dev-bot` failed to do it because `master` is a protected branch. Currently I'm updating versions manually.

I'll figure out a way to update version automatically.

**Comment by cristianmtr** [comment]
I think this was a security vulnerability we noticed

**Comment by nan-wang** [comment]
> I think this was a security vulnerability we noticed

No worry. The bot has its own token.
