### ISSUE TITLE
the latest versions are not available when switching to previous version

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/docs#129]
After switching to `1.0.0`, the versions afterwards are no longer selectable.

![image](https://user-images.githubusercontent.com/4329072/108847521-c4540500-761a-11eb-8025-7b5057be2c8a.png)

**Comment by bwanglzu** [comment]
@Nan-wang this is an expected behavior. When visiting 1.0.0, we're calling the back up version of the docs. So the content and table of content were generated at the release time of 1.0.0. And we do not have future versions yet.

**Comment by nan-wang** [comment]
yes, I understand why it is the case. However, I think it is not the standard way for documentation websites.
