### ISSUE TITLE
remove robots.txt files for older versions

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/docs#142]
Currently, we keep older versions of our robots.txt in each release.
That does not harm but it would be nice to clean them up automatically.

**Comment by FionnD** [comment]
Hey @florian-hoenicke , 

Thanks for noting this. As you said, this is nice to have. So let's add this a good_first_issue and leave it in the public backlog

**Comment by himanshu007-creator** [comment]
hi, I would like to work on this issue🙂
can someone guide me on which older versions are you referring to?
