### ISSUE TITLE
add sitemaps to the robots.txt automatically for new versions

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/docs#143]
Currently, we have to add sitemaps for older versions manually.
Please automize this step by generating the robots.txt file in the script instead of having it directly in the repo.

User-agent: *
Disallow:
sitemap: https://docs.jina.ai/sitemap.xml
sitemap: https://docs.jina.ai/v1.0.10/sitemap.xml

Moreover, the sitemap.xml needs to be adjusted to its actual version.
Example:
We have the following sitemap:
```
User-agent: *
Disallow:
sitemap: https://docs.jina.ai/sitemap.xml
```
Now, we do a release. Means, `sitemap: https://docs.jina.ai/sitemap.xml` becomes `sitemap: https://docs.jina.ai/v1.0.10/sitemap.xml` and we create a new sitemap for the new master `sitemap: https://docs.jina.ai/sitemap.xml`

```
User-agent: *
Disallow:
sitemap: https://docs.jina.ai/sitemap.xml
sitemap: https://docs.jina.ai/v1.0.10/sitemap.xml
```

In addition, the links inside `https://docs.jina.ai/v1.0.10/sitemap.xml` have to be updated to `v1.0.10`.

UAC
- [ ] robots.txt is automatically generated and updated
- [ ] the links inside the sitemaps are updated

**Comment by FionnD** [comment]
Hey @florian-hoenicke , 
Thanks for the heads up. This is clearly a priority to automate this. I've added this to this sprint.

**Comment by florian-hoenicke** [comment]
@FionnD FYI, I updated the ticket description to make it more clear.
