### ISSUE TITLE
Sitemaps for old versions

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/docs#144]
create sitemaps for older versions and add them to the robots.txt
User-agent: *
Disallow:
sitemap: https://docs.jina.ai/sitemap.xml
sitemap: https://docs.jina.ai/v1.0.4/sitemap.xml
sitemap: https://docs.jina.ai/v1.0.3/sitemap.xml
sitemap: https://docs.jina.ai/v1.0.2/sitemap.xml
sitemap: https://docs.jina.ai/v1.0.1/sitemap.xml
sitemap: https://docs.jina.ai/v1.0.0/sitemap.xml

**Comment by FionnD** [comment]
Hey @florian-hoenicke ,

Thanks for noting this. This is nice to have, at least our current version will be created indexed. So let's add this a good_first_issue and leave it in the public backlog

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by bwanglzu** [comment]
hi @himanshu007-creator please do not work on this repo anymore, this is the jina 1.0 documentation. If you want to contribute please find something [here](https://github.com/jina-ai/jina/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
