### ISSUE TITLE
[Suggestion] Add a new github action to assign the issues.

### ISSUE THREAD

**Issue by yashika51** [jina-ai/docs#158]
Hi,
Right now we have few actions already but it would be great to see an action that can be used to assign issues. 

For example, I opened this issue as a suggestion or reporting a bug and I or someone else wants to work on it. They can simply comment `Take` or `Assign me` and they would be assigned to work on the issue automatically. I'd like to work on this if this would be useful and we can start by adding it here later expanding to other repositories. 

I'd love to know your thoughts. Thanks!

**Comment by bwanglzu** [comment]
hi @yashika51 great to hear from you! I think @FionnD is going to answer you, he manages the issues and labels for this repo.

**Comment by Yongxuanzhang** [comment]
Is this a suggestion for docs repo or for all reops? I think this is a good idea.

**Comment by FionnD** [comment]
Hey @yashika51 

Thanks for the suggestion! Maybe I'm missing something, but I can't quite see the advantage of automating this, can you not just assign yourself the issue normally in the **assignees** section?

**Comment by yashika51** [comment]
Thanks for the reply @bwanglzu @Yongxuanzhang and @FionnD. 

@FionnD I don't think a person who is not a collaborator of this repository(or any other repository) can assign issues to themselves. 

My thought behind the idea is if a person wants to work on an issue and is already working on it without claiming(or assigning themselves) another person can take that issue and start working as well and this would lead to duplicate work in the end.

**Comment by FionnD** [comment]
Hey @yashika51 

Uh you were right, my mistake! 

I 100% agree with you that this is important to prevent duplicate work, and correctly reflect that people are contributing :). I just checked with our CEO & CTO about why they set the permission structure this way... maybe it's possible it turns the permission on without having to code a solution. I'm generally a fan of solving a problem without code if possible :D. Once I get a reply I'll post it here! 

If you are interested in building GitHub actions to improve our system, there is a couple of other tickets we have that might also be of interest to you.

**Comment by yashika51** [comment]
Of course. That makes sense. Thanks for the prompt reply.
