### ISSUE TITLE
update my_first_jina_app since cookiecutter is going to be removed

### ISSUE THREAD

**Issue by Yongxuanzhang** [jina-ai/docs#162]
We can use the code in the example repo instead.
https://github.com/jina-ai/docs/blob/master/chapters/my_first_jina_app.md
https://github.com/jina-ai/examples
![image](https://user-images.githubusercontent.com/44033547/110353477-1cb8d880-8005-11eb-87fd-2cf6836a20fb.png)

**Comment by atibaup** [comment]
Hi @Yongxuanzhang - I'm following the tutorial and will be happy to take on this issue, but I'm not sure I understand the problem.

I see that the `jina hub` command uses the cookiecutter template to create a new app:

https://github.com/jina-ai/jina/blob/18b1db9e375f4e43aa8d3c080671b6b5b0b21a99/jina/docker/hubio.py#L107

But in this issue title you say that cookiecutter is going to be removed, and that we can use the code in the https://github.com/jina-ai/examples/tree/master/wikipedia-sentences example instead.

Do you mean that you would like the first app tutorial to not rely on `jina hub new` at all, and that the tutorial should reproduce the code in https://github.com/jina-ai/examples/tree/master/wikipedia-sentences instead?

Thanks :)

**Comment by Yongxuanzhang** [comment]
Hi @atibaup, thank you so much for taking this issue!
Yes, that's what I mean. 
There are two ways:
1) Fully update the template in cookiecutter to make it consistent with our doc;
2) Remove the cookiecutter part in doc, and instead refer to the code in the example [repo](https://github.com/jina-ai/examples/tree/master/wikipedia-sentences)
I would prefer the 2). 
One reason is cookiecutter will not be used in the future (replaced by another one), and another is I think the code in example is easier to maintain.
We can wait for other people's comments. 😄 
@FionnD @alexcg1 @deepankarm

**Comment by alexcg1** [comment]
Hey all! We were discussing this in our Slack today and figured one way to go is to create an empty template and user can work from there. We can rewrite My First Jina App accordingly.

I've already created [the template](https://github.com/jina-ai/examples/pull/423) (I didn't see this thread before - whoops!) but I'm more than happy for @atibaup to handle rewriting the doc itself

**Comment by atibaup** [comment]
Hi! Apologies for slow response - been super busy these days! I'll check the template as @alexcg1 suggests and will attempt to rewrite the docs. Thanks!

**Comment by atibaup** [comment]
Also - I'd be curious to know why you're deprecating cookiecutter and what other templating tool you plan on using instead?

**Comment by alexcg1** [comment]
Hey @atibaup! We had quite a few users facing difficulty with our My First Jina App as it was written, so I took the matter on as urgent. It's pretty much done for now, and the doc and template are fully done and dusted.

We are looking at writing a lot of other tutorials for learning Jina though. I suggest you join our [Slack community](https://slack.jina.ai) and talk to us on the documentation channel there. That might prove faster than doing so here

**Comment by alexcg1** [comment]
Fixed by #187, #183
