### ISSUE TITLE
Improve documentation on Document type and tags as as field to contain meta info

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/docs#163]
I guess we need better documentation for this.

_Originally posted by @JoanFM in https://github.com/jina-ai/jina/issues/1496#issuecomment-748514524_

**Comment by FionnD** [comment]
### UPDATED ISSUE REQUIREMENTS

A [tutorial](https://github.com/jina-ai/docs/blob/master/page_templates/developer_guide_how_to.md) should be written for the documentation site. It should explain how a user correctly use metainfo (tags) in their search system.
