### ISSUE TITLE
Explain JinaRuntime

### ISSUE THREAD

**Issue by FionnD** [jina-ai/docs#164]
As we add more JinaRuntime(s) to the core of Jina, we should explain this concept in the documentation. 

Tasks: 
1. Add an [explanation](https://github.com/jina-ai/docs/blob/master/page_templates/developer_guide_explanation.md) article about the purpose of JinaRuntime. 
2. Add definition of JinaRuntime to the glossary

**Comment by Yongxuanzhang** [comment]
Should this be a separate section in Docs-core? I remembered we should have one section explaining pea&pods. runtime and pea&pods can be explained together I think.

**Comment by Yongxuanzhang** [comment]
I think it's also a good idea to refer items in https://docs.jina.ai/chapters/glossary/ to corresponding explanation sections like the `chunk` item

**Comment by FionnD** [comment]
Yes, your right @Yongxuanzhang ! Good catch. I forget about the ticket. 

I'm closing that ticket and added the task to https://github.com/jina-ai/jina/issues/2084 

And yes, runtime should be added to the glossary and linked back.
