### ISSUE TITLE
Minimum working example...isn't?

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/docs#258]
The [minimum working example](https://docs.jina.ai/chapters/extend/mwu/) should be something more like a minimum working example of a Jina app, no? So basic index and query Flows, like Wikipedia.

The current doc is more of a minimum working example of an Executor. I'm happy to re-title and move if no-one has objections.

**Comment by FionnD** [comment]
You are correct. I would remove it from the public view for the moment.
