### ISSUE TITLE
Create a Jina Tutorial 

### ISSUE THREAD

**Issue by FionnD** [jina-ai/docs#261]
**User story:** 
As a user of Jina I would like to learn how to build a Jina app in a step-by-step manner. Initially, this should cover building a text app, in the future, it should cover other modalities. 

- [x] Create a Design document 
- [x] Set up meeting dev role about hosting tutorials 
- [ ] Decide on topic 
- [ ] Start writing 
- [ ] In review

**Comment by CatStark** [comment]
Already had a call with @pswu11 and it seems we will host the tutorials where the cookbooks. She'll get back to me with confirmation.
