### ISSUE TITLE
Improve chapters folder. 

### ISSUE THREAD

**Issue by FionnD** [jina-ai/docs#87]
**Currently**: 
Our chapters folder has some files directly stored in chapters: `chapters/pod_page.md`
and some in their own folders: `chapters/pod_page/index.md`

In certain cases, this is to allow for local images to be stored in the chapter, but no always. 

**Problems**: 
1. Inconsistent file naming affects SEO. 
2. Confusion for new developers adding files. 
3. Images will be duplicated across folders. (Two folders using the same image). 
4. [Does not follow best web design practice](https://webstyleguide.com/wsg3/5-site-structure/3-site-file-structure.html) 

**Solution**: 
1. Create a folder for images `chapters/images/`
2. Move all images (.png/.gif etc) to that folder. 
3. Move all files to the root of the chapter folder. A file like `chapters/pods/pod_page.md` should be moved to `chapters/pod_page.md`. This might require renaming some files. 
4. When a file has been moved, the TOC should be updated. 
3. Update all files in the chapter folder so images are correctly shown. For example, a which has `.. image:: magnetic-balls.jpg `should be updated to `.. image:: ../images/magnetic-balls.jpg`

**Comment by ThePfarrer** [comment]
Hi @FionnD! 
Does this apply to folders that contain only one file or also to the files within the subfolder in a folder? 
For example, `chapters/101/` has only one file while `chapters/box/` has three(3) subfolders, each containing one file.  Should those files also be moved to the root chapter folder?

Also, what is the preferred naming convention? For example, `chapters/101/`  and `chapters/102/` both have files called `index.rst`. How should they be renamed to avoid one file overwriting the other?

**Comment by FionnD** [comment]
Good questions @ThePfarrer !

> Does this apply to folders that contain only one file or also to the files within the subfolder in a folder?
> For example, `chapters/101/` has only one file while `chapters/box/` has three(3) subfolders, each containing one file. Should those files also be moved to the root chapter folder?

The chapters `dashboard, box, hub, core `should be excluded from this issue. They are special. 

> Also, what is the preferred naming convention? For example, `chapters/101/` and `chapters/102/` both have files called `index.rst`. How should they be renamed to avoid one file overwriting the other?

We don't have a standard naming convention (yet). So can you just choose what you think is most suited. :)
