### ISSUE TITLE
Improve SEO 

### ISSUE THREAD

**Issue by FionnD** [jina-ai/docs#91]
Read this [guide](https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html#optimizing-your-docs-for-search-engine-spiders) and implement any of the possible steps.

For example, try adding a robot.txt file according to the [instructions](https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html#use-a-robots-txt-file).

**Comment by bwanglzu** [comment]
one easy trick is to add meta to `reST` based documents like [this](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#html-metadata)

**Comment by ThePfarrer** [comment]
> For example, try adding a robot.txt file according to the [instructions](https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html#use-a-robots-txt-file).

@FionnD is there a specific customization? Because Read the Docs seems to automatically create a robot.txt file.
